"""New other column

Revision ID: 99977ae5426e
Revises: 2d8f63c0c219
Create Date: 2018-12-07 12:39:08.246526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99977ae5426e'
down_revision = '2d8f63c0c219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('other', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'other')
    # ### end Alembic commands ###
