const movies = [
  'Ben-Hur',
  'Gone with the Wind',
  'Vreme na nasilie',
  'The English Patient',
  'Schindler\'s List',
  'Saving Private Ryan',
  'The Deer Hunter',
  'The Elephant Man',
  'Midnight Express',
  'Titanic',
  'The Aviator',
  'Terms of Endearment',
  'American Beauty',
  'Forrest Gump',
  'Amadeus',
  'One Flew Over the Cuckoo\'s Nest',
  'Braveheart',
  'Gladiator',
  'Scarface',
  'There Will Be Blood',
  'The Godfather',
  'The Godfather: Part II',
  'The Pianist',
  'Das Boot',
  'Der Untergang',
  'Das Leben der Anderen',
  'Ladri di biciclette',
  'The Best Years of Our Lives',
  'To Kill a Mockingbird',
  'It\'s a Wonderful Life',
  'All About Eve',
  'On the Waterfront',
  'A Streetcar Named Desire',
  'The Sting',
  'Kramer vs. Kramer',
  'Ordinary People',
  'As Good as It Gets',
  'Groundhog Day',
  'Fight Club',
  'Gattaca',
  'The Matrix',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Lord of the Rings: The Two Towers',
  'The Lord of the Rings: The Return of the King',
  'Avatar',
  'El laberinto del fauno',
  'Syriana',
  'The Talented Mr. Ripley',
  'Heat',
  'The Insider',
  'Goodfellas',
  'Casino',
  'The Departed',
  'Gangs of New York',
  'Raging Bull',
  'Taxi Driver',
  'Falling Down',
  'The Good Son',
  'Devil\'s Advocate',
  'Philadelphia',
  'The Shawshank Redemption',
  'Eyes Wide Shut',
  'Full Metal Jacket',
  'Barry Lyndon',
  'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
  'Paths of Glory',
  'Spartacus',
  'The Shining',
  'A Clockwork Orange',
  '2001: A Space Odyssey',
  'Lolita',
  'The Killing',
  'Letyat zhuravli',
  'Z',
  'The Day of the Jackal',
  'Chinatown',
  'The Bridge on the River Kwai',
  'Doctor Zhivago',
  'Lawrence of Arabia',
  'A Passage to India',
  'Gandhi',
  'The Last Emperor',
  'Reds',
  'Okuribito',
  'A Man for All Seasons',
  'High Noon',
  'Apocalypse Now',
  'Dracula',
  'The Silence of the Lambs',
  'Network',
  'Dog Day Afternoon',
  '12 Angry Men',
  'The Grapes of Wrath',
  'The Searchers',
  'Once Upon a Time in America',
  'C\'era una volta il West',
  'Il buono il brutto il cattivo',
  'Butch Cassidy and the Sundance Kid',
  'Unforgiven',
  'Mystic River',
  'Million Dollar Baby',
  'A Beautiful Mind',
  'Jodaeiye Nader az Simin',
  '12 Years a Slave',
  'The King\'s Speech',
  'Nuovo Cinema Paradiso',
  'Svetat e golyam i spasenie debne otvsyakade',
  'Viva Zapata!',
  'Cat on a Hot Tin Roof',
  'Notorious',
  'Rashômon',
  'Shichinin no samurai',
  'Tasogare Seibei',
  'Da hong deng long gao gao gua',
  'Ying xiong',
  'Batoru rowaiaru',
  'Gongdong gyeongbi guyeok JSA',
  'Salinui chueok',
  'Inglourious Basterds',
  'Kill Bill: Vol. 1',
  'Kill Bill: Vol. 2',
  'Pulp Fiction',
  'Reservoir Dogs',
  'Django Unchained',
  'JFK',
  'Any Given Sunday',
  'Wall Street',
  'Natural Born Killers',
  'Platoon',
  'Born on the Fourth of July',
  'Dead Poets Society',
  'Rain Man',
  'Broadcast News',
  'Mississippi Burning',
  'In the Heat of the Night',
  'The Last Picture Show',
  'The Getaway',
  'Guess Who\'s Coming to Dinner',
  'Midnight Cowboy',
  'Cool Hand Luke',
  'The Graduate',
  'Breakfast at Tiffany\'s',
  'Alexis Zorbas',
  'Rocky',
  'Lenny',
  'Marathon Man',
  'Ragtime',
  'La vita è bella',
  'The Remains of the Day',
  'Malèna',
  'La ciociara',
  'La strada',
  'Fargo',
  'No Country for Old Men',
  'The Big Lebowski',
  'Burn After Reading',
  'Adaptation.',
  'Little Miss Sunshine',
  'Mr. Nobody',
  'Cloud Atlas',
  'Being John Malkovich',
  'Rear Window',
  'Psycho',
  'Donnie Darko',
  'Rosemary\'s Baby',
  'The Sixth Sense',
  'Mulholland Dr.',
  'Blue Velvet',
  'The Others',
  'Dogville',
  'Blood Diamond',
  'The Last King of Scotland',
  'Hotel Rwanda',
  'Man on Fire',
  'Training Day',
  'Léon',
  'American Psycho',
  'The Game',
  'Snatch.',
  'Lock',
  'Tsotsi',
  'Cidade de Deus',
  'Slumdog Millionaire',
  'El secreto de sus ojos',
  'Hable con ella',
  'Los abrazos rotos',
  'Volver',
  'Todo sobre mi madre',
  'La mala educación',
  'La piel que habito',
  'Mar adentro',
  'Her',
  'Vanilla Sky',
  'The Beach',
  'Great Expectations',
  'Good Will Hunting',
  'Scent of a Woman',
  'Reality Bites',
  'What\'s Eating Gilbert Grape',
  'The Straight Story',
  'About Schmidt',
  'Lost in Translation',
  'Moneyball',
  'Eternal Sunshine of the Spotless Mind',
  'L.A. Confidential',
  'The Usual Suspects',
  'The French Connection',
  'The Untouchables',
  'Witness',
  'Blow',
  'Big Fish',
  'Le fabuleux destin d\'Amélie Poulain',
  'Ondskan',
  'Låt den rätte komma in',
  'Lagaan: Once Upon a Time in India',
  'The Help',
  'Into the Wild',
  'Revolutionary Road',
  'Road to Perdition',
  'Amores perros',
  '21 Grams',
  'Babel',
  'Hævnen',
  'Jagten',
  'Munich',
  'The Fighter',
  'Magnolia',
  'Traffic',
  'Apocalypto',
  'Crash',
  'The Prestige',
  'Memento',
  'Black Swan',
  'The Wrestler',
  'Kolja',
  'In the Name of the Father',
  'The Social Network',
  'The Green Mile',
  'E.T. the Extra-Terrestrial',
  'Artificial Intelligence: AI',
  'Catch Me If You Can',
  'The Pursuit of Happyness',
  'Seven Pounds',
  'Capote',
  'Doubt',
  'The Truman Show',
  'Sling Blade',
  'Dances with Wolves',
  'Cold Mountain',
  'Dangerous Liaisons',
  'The Piano',
  'La veuve de Saint-Pierre',
  'De tweeling',
  'Citizen Kane',
  'The Apartment',
  'Roman Holiday',
  'The Lost Weekend',
  'Le salaire de la peur',
  'Les quatre cents coups',
  'Belle de jour',
  'Le charme discret de la bourgeoisie',
  'La battaglia di Algeri',
  'The Great Escape',
  'Casablanca',
  'The Treasure of the Sierra Madre',
  'The African Queen',
  'The Man Who Would Be King',
  'Master and Commander: The Far Side of the World',
  'The Mission',
  'Glory',
  'Raiders of the Lost Ark',
  'Amistad',
  'War Horse',
  'The Color Purple',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'Troy',
  'Australia',
  'Wo hu cang long',
  'Elizabeth',
  'American History X',
  'La haine',
  'The Verdict',
  'Erin Brockovich',
  'Trainspotting',
  'The Acid House',
  'Rise of the Footsoldier',
  'Nikita',
  'Se7en',
  'The Fugitive',
  'Mission: Impossible',
  'Peeping Tom',
  'The Exorcist',
  'Carrie',
  'Alien',
  'Blade Runner',
  'Brazil',
  'Twelve Monkeys',
  'The Reader',
  'The Constant Gardener',
  'Atonement',
  'Up in the Air',
  'The Assassination of Jesse James by the Coward Robert Ford',
  'Letters from Iwo Jima',
  'Dirty Pretty Things',
  'Inside Man',
  'True Lies',
  'Terminator 2: Judgment Day',
  'Aliens',
  'The Abyss',
  'Contact',
  'Inception',
  'Insomnia',
  'The Bourne Identity',
  'Jackie Brown',
  'Miller\'s Crossing',
  'U Turn',
  'I Am Sam',
  'Mamma Mia!',
  'Spanglish',
  'In Bruges',
  'The Next Three Days',
  'Biutiful',
  'The Artist',
  'The Master',
  'Boogie Nights',
  'The People vs. Larry Flynt',
  'Man on the Moon',
  'Cast Away',
  'Flight',
  'The Devil Wears Prada',
  'Before the Devil Knows You\'re Dead',
  '25th Hour',
  '127 Hours',
  '28 Days Later...',
  'Unbreakable',
  'The Girl with the Dragon Tattoo',
  'The Man Who Wasn\'t There',
  'Cinderella Man',
  'The Hours',
  'Intouchables',
  'Le scaphandre et le papillon',
  'Incendies',
  'Un prophète',
  'Joyeux Noël',
  'No Man\'s Land',
  'Before the Rain',
  'Paradise Now',
  'Diarios de motocicleta',
  'Nirgendwo in Afrika',
  'Der Tunnel',
  'Amen.',
  'Sophie Scholl - Die letzten Tage',
  'Katyn',
  'Revanche',
  'Die Welle',
  'Zwartboek',
  'Die Fälscher',
  'Auf der anderen Seite',
  'Bloody Sunday',
  'Hard Candy',
  'Juno',
  'Almost Famous',
  'Notes on a Scandal',
  'Sideways',
  'Moon',
  'Jaws',
  'The Poseidon Adventure',
  'Deliverance',
  'Planet of the Apes',
  'Papillon',
  'Serpico',
  'The Conversation',
  'Dirty Harry',
  'Bonnie and Clyde',
  'The Producers',
  'Blazing Saddles',
  'Monty Python and the Holy Grail',
  'Life of Brian',
  'Murder on the Orient Express',
  'American Graffiti',
  'Straw Dogs',
  'Annie Hall',
  'Hair',
  'The Omen',
  'Vsichko e lyubov',
  'Un homme et une femme',
  'Missing',
  'The Killing Fields',
  'Empire of the Sun',
  'Indochine',
  'Music Box',
  'Cry Freedom',
  'La leggenda del pianista sull\'oceano',
  'The Agony and the Ecstasy',
  'Sleuth',
  'The Wicker Man',
  'Five Easy Pieces',
  'The Driver',
  'North by Northwest',
  'Vertigo',
  'Anatomy of a Murder',
  'The Hustler',
  'Easy Rider',
  'The Manchurian Candidate',
  'Judgment at Nuremberg',
  'The Boys from Brazil',
  'Le cercle rouge',
  'Le samouraï',
  'Le professionnel',
  'The Magnificent Seven',
  'The Thomas Crown Affair',
  'Bullitt',
  'Atlantic City',
  'Blood Simple.',
  'Trading Places',
  'Sex Lies and Videotape',
  'Spy Game',
  'The Machinist',
  'The Curious Case of Benjamin Button',
  'Argo',
  'In the Bedroom',
  'Walk the Line',
  '(500) Days of Summer',
  'The Ides of March',
  'Charlie Wilson\'s War',
  'The Iceman',
  'A History of Violence',
  'V for Vendetta',
  'Taken',
  'American Gangster',
  'Body of Lies',
  'Desperado',
  'From Dusk Till Dawn',
  'The Faculty',
  'Shaun of the Dead',
  'Starship Troopers',
  'Point Break',
  'Boys Don\'t Cry',
  'Donnie Brasco',
  'Carlito\'s Way',
  'Leaving Las Vegas',
  'Ghost',
  'The Player',
  'Thelma and Louise',
  'True Romance',
  'Do the Right Thing',
  'The Crying Game',
  'Heathers',
  'A Fish Called Wanda',
  'Reversal of Fortune',
  'Working Girl',
  'Tootsie',
  'The King of Comedy',
  'Cape Fear',
  'The Crow',
  'Malcolm X',
  'A Bronx Tale',
  'Animal Kingdom',
  'Lincoln',
  'The Great Debaters',
  'Boyz n the Hood',
  'Dead Man Walking',
  'Fatal Attraction',
  'Basic Instinct',
  'Jerry Maguire',
  'A Few Good Men',
  'Primal Fear',
  'Gridlock\'d',
  'October Sky',
  'Pay It Forward',
  'Est - Ouest',
  'Election',
  'The Ghost Writer',
  'Eastern Promises',
  'Punch-Drunk Love',
  'The Station Agent',
  'Le capital',
  'Birdman: Or (The Unexpected Virtue of Ignorance)',
  'The Grand Budapest Hotel',
  'Whiplash',
  'Foxcatcher',
  'Kill the Messenger',
  'A Most Violent Year',
  'Le dernier diamant',
  'Nightcrawler',
  'Ed Wood',
  'Lethal Weapon',
  'Glengarry Glen Ross',
  'Misery',
  'Ôdishon',
  'Tesis',
  'Top Gun',
  'Bumer',
  'War of the Worlds',
  'Children of Men',
  'Gravity',
  'District 9',
  'Zero Dark Thirty',
  'Captain Phillips',
]

export function getRandomMovie(){
  return movies[Math.floor(Math.random()*movies.length)];
}
