FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y -q sudo
RUN apt-get install -y -q fail2ban
RUN apt-get install -y -q httpie
RUN apt-get install -y -q glances

RUN apt-get install -y -q build-essential git python3-pip python3-dev python3-venv
RUN python3 -m venv /venv
RUN /venv/bin/pip install -U pip setuptools
RUN /venv/bin/pip install responder

COPY movie_svc /app
WORKDIR /app
RUN /venv/bin/pip install -r /app/requirements.txt

ENTRYPOINT /venv/bin/python /app/app.py
