# Generated by Django 2.1 on 2018-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='inspiration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
