# Generated by Django 2.1 on 2018-08-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20180828_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='inspiration',
        ),
    ]
