"""Adds bills.last_payment column

Revision ID: 2d8f63c0c219
Revises: 
Create Date: 2018-12-07 12:35:58.577693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8f63c0c219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('last_payment', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bills_last_payment'), 'bills', ['last_payment'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_last_payment'), table_name='bills')
    op.drop_column('bills', 'last_payment')
    # ### end Alembic commands ###
